
# Uygulama Portu
server.port=8080

# H2 Veritaban? Ayarlar?
spring.datasource.url=jdbc:h2:mem:spotidb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Hibernate / JPA Ayarlar?
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# Tablolar?n entity'lere göre otomatik güncellenmesini sa?lar
spring.jpa.hibernate.ddl-auto=update
# Konsolda çal??t?r?lan SQL sorgular?n? görmek için
spring.jpa.show-sql=true

# H2 Console Ayarlar? (Taray?c?dan veritaban?n? arayüzünü görmek için)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console